apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
bases:
  - ../../../base

resources:
  - pv.yml
  - pvc.yml

patchesStrategicMerge:
  - dep.yml
  - svc.yml

configMapGenerator:
  - name: nginx.conf
    files:
      - nginx.conf
  - name: retrieve_certificate-sh
    files:
      - retrieve_certificate.sh

commonLabels:
    app: nginx
