apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nginx
  ports:
  - name: "nginx-http"
    targetPort: 80
    port: 80
  loadBalancerIP:
    192.168.50.150
