apiVersion: v1
kind: PersistentVolume
metadata:
    name: tautulli-plex
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    storageClassName: nfs
    nfs:
        path: /mnt/DataPool/Kubernetes/Plex/config/Library/Application Support/Plex Media Server/Logs
        server: earth.sol.milkyway
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: tautulli-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    storageClassName: nfs
    nfs:
        path: /mnt/DataPool/Kubernetes/Tautulli/
        server: earth.sol.milkyway
