apiVersion: v1
kind: PersistentVolume
metadata:
    name: bitwardenrs-data
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/Bitwarden_rs/data/
        server: earth.sol.milkyway
    storageClassName: nfs
