apiVersion: v1
kind: Service
metadata:
  labels:
    app: bitwardenrs
  name: bitwardenrs
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: bitwardenrs
  ports:
  - name: "http-web"
    targetPort: 80
    port: 80
  loadBalancerIP:
    192.168.50.163
