apiVersion: v1
kind: PersistentVolume
metadata:
    name: personal-website-files
    labels:
        app: personal-website
        pv: personal-website-files
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadOnlyMany
    nfs:
        server: saturn.sol.milkyway
        path: "/SaturnPool/Kubernetes/Apache/Files/"
