apiVersion: v1
kind: PersistentVolume
metadata:
    name: personal-website-files
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadOnlyMany
    storageClassName: nfs
    hostPath:
        path: /DataPool/Kubernetes/Apache/Files
