apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab

resources:
  - dep.yml
  - pv.yml
  - pvc.yml
  - svc.yml

secretGenerator:
  - name: gitlab-redis-password
    envs:
      - redis_password

commonLabels:
    app: redis
