apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-redis-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: gitlab-redis-data
