apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bitwardenrs

resources:
  - dep.yml
  - pv.yml
  - pvc.yml
  - svc.yml

configMapGenerator:
  - name: bitwardenrs-postgres-env-vars
    literals:
      - POSTGRES_USER=bitwardenrs

secretGenerator:
  - name: bitwardenrs-postgres-password
    envs:
      - postgres_password

commonLabels:
    app: postgres
