apiVersion: v1
kind: PersistentVolume
metadata:
    name: radarr-config
spec:
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
    storageClassName: nfs
    nfs:
        path: /mnt/DataPool/Kubernetes/Radarr
        server: earth.sol.milkyway
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#     name: radarr-fileserver
# spec:
#     capacity:
#         storage: 15Ti
#     accessModes:
#         - ReadWriteMany
#     hostPath:
#         path: /mnt/DataPool/
    # storageClassName: nfs
    # nfs:
    #     path: /mnt/DataPool/Kubernetes/ruTorrent
    #     server: earth.sol.milkyway
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: radarr-movies
spec:
    capacity:
        storage: 15Ti
    accessModes:
        - ReadWriteMany
    storageClassName: nfs
    nfs:
        path: /mnt/DataPool/Movies
        server: earth.sol.milkyway
