apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab
bases:
  - ../../../base

resources:
  - pv.yml
  - pvc.yml

patchesStrategicMerge:
  - dep.yml
  - svc.yml

secretGenerator:
  - name: gitlab-password
    envs:
      - gitlab_password
  - name: gitlab-omnibus-config
    files:
      - gitlab_omnibus_config

configMapGenerator:
  - name: gitlab-env-vaars
    literals:
      # - ENABLE_BOOTSNAP=1
      # - GITLAB_CDN_HOST='gitlab.tjzimmerman.com'
      - GITLAB_HOST='https://gitlab.tjzimmerman.com'
      - GITLAB_EMAIL_DISPLAY_NAME='hyperion'
      - GITLAB_EMAIL_FROM='hyperion@tjzimmerman.com
      # - GITLAB_UNICORN_MEMORY_MAX=''
      # - GITLAB_UNICORN_MEMORY_MIN=''

commonLabels:
    app: gitlab
