apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitlab-data
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/GitLab/data/
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitlab-config
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/GitLab/config/
        server: earth.sol.milkyway
    storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: gitlab-logs
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteMany
    nfs:
        path: /mnt/DataPool/Kubernetes/GitLab/logs/
        server: earth.sol.milkyway
    storageClassName: nfs
