apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: saturnpool
allowVolumeExpansion: true
parameters:
  fstype: "zfs"
  poolname: "SaturnPool"
  recordsize: "4k"
provisioner: zfs.csi.openebs.io
