apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../base/

resources:
    - pv.yml
    - pvc.yml
    - rq.yml

patchesStrategicMerge:
    - dep.yml
    - svc.yml
    - ns.yml

namespace: sonarr

commonLabels:
    app: sonarr

configMapGenerator:
    - name: sonarr-env-vars
      literals:
        - TZ='America/Los_Angeles'
        - PUID='1002'
        - PGID='1007'

