apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rutorrent
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      containers:
        - name: rutorrent
          image: crazymax/rtorrent-rutorrent
          envFrom:
            - configMapRef:
                name: rutorrent-env-vars
          ports:
            - name: "rutorrent-web"
              containerPort: 8080
              protocol: TCP
            - name: "rutorrent-hc"
              containerPort: 8081
              protocol: TCP
            - name: "rutorrent-wd"
              containerPort: 9000
              protocol: TCP
            - name: "rutorrent-bt"
              containerPort: 50000
              protocol: TCP
            - name: "rutorrent-xml"
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: rutorrent-config
              mountPath: /data
            - name: rutorrent-fileserver
              mountPath: /datapool
      volumes:
        - name: rutorrent-config
          persistentVolumeClaim:
            claimName: rutorrent-config
        - name: rutorrent-fileserver
          persistentVolumeClaim:
            claimName: rutorrent-fileserver
