apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
    - ../../../base/

resources:
    - pv.yml
    - pvc.yml
    - svc_tcp.yml

images:
  - name: crazymax/rtorrent-rutorrent
    newTag: latest

patchesStrategicMerge:
    - dep.yml

namespace: rutorrent

configMapGenerator:
    - name: rutorrent-env-vars
      literals:
        - TZ='America/Los_Angeles'
        - PUID='1002'
        - PGID='1007'
        - RU_HTTP_TIME_OUT=60
        - RU_RPC_TIME_OUT=10
