# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: rutorrent-downloads
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 10Ti
#   volumeName: rutorrent-downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-fileserver
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Ti
  volumeName: rutorrent-fileserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-config
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: rutorrent-config
