apiVersion: v1
kind: Service
metadata:
  name: rutorrent-tcp
  labels:
    app: rutorrent
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.152
  selector:
    app: rutorrent
  ports:
  - name: "rutorrent-web"
    protocol: TCP
    targetPort: 8080
    port: 80
  - name: "rutorrent-hc"
    protocol: TCP
    targetPort: 8081
    port: 8081
  - name: "rutorrent-wd"
    protocol: TCP
    targetPort: 9000
    port: 9000
  - name: "rutorrent-bt"
    protocol: TCP
    targetPort: 50000
    port: 50000
  - name: "rutorrent-xml"
    protocol: TCP
    targetPort: 8000
    port: 8000