apiVersion: v1
kind: Service
metadata:
  name: rutorrent-tcp
  annotations:
      metallb.universe.tf/allow-shared-ip: "true"
  labels:
    app: rutorrent
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.50.151
  selector:
    app: rutorrent
  ports:
  - name: "rutorrent-web"
    protocol: TCP
    targetPort: 80
    port: 80
  - name: "rutorrent-scgi"
    protocol: TCP
    targetPort: 5000
    port: 5000
  - name: "rutorrent-bt"
    protocol: TCP
    targetPort: 51413
    port: 51413

